### ISSUE TITLE
Plantage serveur

### ISSUE THREAD

**Issue by amelaye** [MT-Goops/rings#1]
Ola,
Il y a des plantages récurrents sur le serv et j'ai trouvé le responsable :)

Voici la trace :

> 2022-05-05 01:08:19: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'goops_rings' in callback environment_Step(): /mypath/.minetest/mods/rings/activation.lua:161: attempt to index a nil value
> 2022-05-05 01:08:19: ERROR[Main]: stack traceback:
> 2022-05-05 01:08:19: ERROR[Main]:       /mypath/.minetest/mods/rings/activation.lua:161: in function 'falling'
> 2022-05-05 01:08:19: ERROR[Main]:       /mypath/.minetest/mods/rings/activation.lua:170: in function </mypath/.minetest/mods/rings/activation.lua:166>
> 2022-05-05 01:08:19: ERROR[Main]:       /pathminetest/builtin/game/register.lua:425: in function </pathminetest/builtin/game/register.lua:409>

**Comment by MT-Goops** [comment]
salut,
en effet c'est même mon personnage qui fait tout buguer. 
Je suis au dessus d'un nœud rouge "undefined" du mod factory (retiré ?) Quand je me connecte ça me remet au même endroit. Il faudrait aller virer le nœud.
La fonction _falling_ regarde les noeuds sous les personnages pour déclencher le vol en mod auto, s'il y a plus de 4 mètres de vide. Je vais essayer de rendre ça plus robuste, je n'avais pas prévu les nœuds non définis !

**Comment by MT-Goops** [comment]
C'est corrigé (et j'ai enlevé des calculs inutiles, j'avais mal codé : il vérifiait tout le temps des trucs alors que le mode auto n'était pas activé)
